"""add ignore flag to user rating

Revision ID: 9ec7707f081b
Revises: e1652bbc11a6
Create Date: 2026-05-28 21:37:13.067266

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9ec7707f081b'
down_revision: Union[str, Sequence[str], None] = 'e1652bbc11a6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""

    op.add_column('userrating', sa.Column('ignore', sa.Boolean(), nullable=True))
    op.execute("UPDATE userrating SET ignore = 0")

    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('userrating') as batch_op:
        batch_op.alter_column('ignore', nullable=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('userrating', 'ignore')
    
    # ### end Alembic commands ###
