"""Add movie_id foreign key to UserRating

Revision ID: e1652bbc11a6
Revises: a39ec09905b7
Create Date: 2026-05-06 19:01:03.683823

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e1652bbc11a6'
down_revision: Union[str, Sequence[str], None] = 'a39ec09905b7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('model_id',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text("'0'"))

    with op.batch_alter_table('userrating', schema=None) as batch_op:
        batch_op.create_foreign_key('fk_userrating_movie_id_movie', 'movie', ['movie_id'], ['id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('userrating', schema=None) as batch_op:
        batch_op.drop_constraint('fk_userrating_movie_id_movie', type_='foreignkey')

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('model_id',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text("'0'"))

    # ### end Alembic commands ###
